const os = require('os');
const meta = require('./meta.js').meta;


let objects = [
  // { m: 'beaver', q: 1 },
  // { m: 'key', q: 1 },
  // { m: 'potatoseed', q: 1 },
  // { m: 'potato', q: 1 },
  // { m: 'seed', q: 1 },
  // { m: 'beside', q: 1 },
  // { m: 'flag', q: 1 },
  // { m: 'antegg', q: 1 },
  // { m: 'dwarf', q: 1 },
  // { m: 'aphidka', q: 1 },
  // { m: 'aphid', q: 1 },
  // { m: 'rot', q: 1 },
  // { m: 'ash', q: 1 },
  // { m: 'fence', q: 1 },
  // { m: 'mermaid', q: 1 },
  // { m: 'orange', q: 1 },
  // { m: 'oranger', q: 1 },
  // { m: 'jackal', q: 1 },
  // { m: 'potatoplant', q: 1 },
  // { m: 'skeleton', q: 5 },
  // { m: 'crab', q: 1 },
  // { m: 'shovel', q: 5 },
  // // { m: 'wolf', q: 1 },
  // { m: 'stone', q: 1 },
  // // { m: 'kaka', q: 1 },
  // { m: 'flinders', q: 1},
  // // { m: 'torch', q: 1 },
  // { m: 'door', q: 1 },
  // { m: 'ant', q: 5 },
  // { m: 'pickaxe', q: 5 },
  // // { m: 'cow', q: 1 },
  // { m: 'tree', q: 10 },
  // // { m: 'treeseed', q: 1 },
  // // { m: 'swamp', q: 1 },
  // { m: 'water', q: 1 },
  // { m: 'fish', q: 1 },
  // // { m: 'plant', q: 1 },
  // // { m: 'train', q: 1 },
  // // { m: 'blackearth', q: 1 },
  // // { m: 'road', q: 1 },
  // { m: 'wall', q: 100 },
  // { m: 'wwall', q: 10 },
  // // { m: 'window', q: 1 },
  // { m: 'fire', q: 1 },
  // // { m: 'orangetree', q: 1 },
  // // { m: 'firedegg', q: 1 },
  // // { m: 'beaveregg', q: 1 },
  // // { m: 'box', q: 1 },
  // // { m: 'axe', q: 1 },
  // { m: 'bone', q: 1 },
  // { m: 'zombie', q: 1 },
  { m: 'highgrass', q: 1 },
  // { m: 'carnivorous', q: 4 },
  // { m: 'stonegolem', q: 1 },
  // { m: 'stick', q: 1 },
  // // { m: 'wood', q: 1 },
  // // { m: 'grill', q: 1 },
  // // { m: 'meat', q: 1 },
];

if (os.platform() == 'darwin' || os.platform() == 'win32') {
  module.exports = {
    ip: "127.0.0.1",
    port: "3000",
    botkey: '320938705:AAGpcdMe9oIhFYuu11MjU4djJnj1maijkpQ',
    savefrequency: 8640000,
    statfrequency: 1000,
    world: {
      start: 5200,
      obj: objects,
      factor: 1,
      items: 100000,
      speed: 10,
    }
  }
} else {
  module.exports = {
    ip: "46.101.23.21",
    port: "80",
    botkey: '602673396:AAFHMT_6QTnuPnDBYNLKDGFiiVnwbvZYYHM',
    savefrequency: 864000,
    statfrequency: 10000,
    world: {
      start: 5200,
      obj: objects,
      factor: 0.5,
      items: 500000,
      speed: 10,
    }
  }
}